name: Build and Push Containers to ACR

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
  API_IMAGE_NAME: liveorderbookapi
  BLAZOR_IMAGE_NAME: liveorderbookblazor

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código-fonte
    - name: Checkout code
      uses: actions/checkout@v3

    # Login no ACR usando Service Principal
    - name: Login to Azure Container Registry
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

    # Construir e enviar a imagem da API
    - name: Build and Push API Image
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.run_number }} -f DockerfileApi .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.run_number }}

    # Construir e enviar a imagem do Blazor
    - name: Build and Push Blazor Image
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.BLAZOR_IMAGE_NAME }}:${{ github.run_number }} -f DockerfileWASM .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.BLAZOR_IMAGE_NAME }}:${{ github.run_number }}
